namespace Aer.Cli;

/// <summary>
/// Parsed arguments for <c>aer redispatch &lt;room-dir&gt;</c> (#1441): reruns a TERMINAL room's
/// single-role dispatch into a fresh room, inheriting <see cref="ParentRoomDirectoryPath"/>'s recorded
/// <c>bindings.json</c> as defaults — see <see cref="RedispatchCommand"/> for how each field below is
/// applied, and spec/baton.md §2 for the command's contract.
/// </summary>
/// <param name="ParentRoomDirectoryPath">The terminal room whose recorded binding this redispatch inherits.</param>
/// <param name="RoomDirectoryPath">
/// The NEW room's directory — always fresh, generated by <see cref="RedispatchOptionsParser"/>, per the
/// same never-reused/never-resumed rule <see cref="DispatchOptionsParser"/> documents for <c>aer dispatch</c>.
/// </param>
/// <param name="SpecFilePath">
/// The amended brief. Null reuses <see cref="ParentRoomDirectoryPath"/>'s recorded prompt verbatim,
/// rather than re-deriving it — see <see cref="RedispatchCommand"/>'s remarks for why.
/// </param>
/// <param name="Adapter">Overrides the parent binding's adapter; null inherits it.</param>
/// <param name="Model">Overrides the parent binding's model; null inherits it (dropped instead on an inherited adapter swap — see <see cref="RedispatchCommand.InheritBinding"/>).</param>
/// <param name="Effort">Overrides the parent binding's effort; null inherits it (same adapter-swap rule as <see cref="Model"/>).</param>
/// <param name="WorkspaceDirectory">Overrides the parent binding's workspace; null inherits it.</param>
/// <param name="OutputPath">
/// A fresh <c>--output</c> override, parsed and validated exactly like <c>aer dispatch</c>'s own. Never
/// inherited from the parent: the destination a prior <c>--output</c> copied to is process-local to that
/// invocation and is not recorded anywhere in the room (<see cref="RedispatchCommand"/>'s remarks).
/// </param>
/// <param name="Timeout">Overrides the parent binding's timeout; null inherits it.</param>
public sealed record RedispatchOptions(
    string ParentRoomDirectoryPath,
    string RoomDirectoryPath,
    string? SpecFilePath = null,
    string? Adapter = null,
    string? Model = null,
    string? Effort = null,
    string? WorkspaceDirectory = null,
    string? OutputPath = null,
    TimeSpan? Timeout = null);
